name: Java CI with Maven

on:
  push:
    tags:
      - '*'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
    - name: Upload JAR
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: /home/runner/work/NewRepo/NewRepo/target/demo-0.0.1-SNAPSHOT.jar
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "demo-0.0.1-SNAPSHOT.jar"

  artifact:
    name: Publish - GitHub Packages
    runs-on: ubuntu-18.04
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven
      - name: Publish artifact on GitHub Packages
        run: mvn -B clean deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
