name: Publish

on:
  release:
    ['create']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11 for Shared Runner
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Publish artifact on GitHub Packages
        run: mvn -B -e -X clean deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
